In [ ]:
import pandas as pd

# Load the raw dataset
df = pd.read_csv("../data/jobstreet_all_job_dataset.csv")
print("Dataset loaded successfully")

Dataset loaded successfully

In [ ]:
# Check the overall dataset dimensions
print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

Total rows: 69024
Total columns: 11

In [ ]:
# Display dataset structure and data types
print("\nDataset information:")
df.info()

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 69024 entries, 0 to 69023
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   job_id        69024 non-null  float64
 1   job_title     69024 non-null  str
 2   company       69024 non-null  str
 3   descriptions  69024 non-null  str
 4   location      69024 non-null  str
 5   category      69024 non-null  str
 6   subcategory   69024 non-null  str
 7   role          66772 non-null  str
 8   type          69024 non-null  str
 9   salary        31594 non-null  str
 10  listingDate   69024 non-null  str
dtypes: float64(1), str(10)
memory usage: 5.8 MB

In [29]:
# Preview the first 5 records of the dataset
df.head()

,job_id,job_title,company,descriptions,location,category,subcategory,role,type,salary,listingDate
0,74630583.0,Procurement Executive (Contract),Coca-Cola Bottlers (Malaysia) Sdn Bhd,Position Purpose\nManage aspects of procuremen...,Negeri Sembilan,"Manufacturing, Transport & Logistics","Purchasing, Procurement & Inventory",procurement-executive,Contract/Temp,NaN,2024-03-21T05:58:35Z
1,74660602.0,Account Executive/ Assistant,Acoustic & Lighting System Sdn Bhd,We are looking for a Account Executive/ Assist...,Petaling,Accounting,Bookkeeping & Small Practice Accounting,executive-assistant,Full time,"RM 2,800 – RM 3,200 per month",2024-03-22T06:52:57Z
2,74655679.0,"Data Analyst - Asset Management, SPX Express",Shopee Mobile Malaysia Sdn Bhd,Performs detailed data analysis on existing sp...,Klang District,"Manufacturing, Transport & Logistics",Analysis & Reporting,asset-management-analyst,Full time,NaN,2024-03-22T04:22:43Z
3,74657624.0,Service Engineer,Sun Medical Systems Sdn Bhd,"You are important for troubleshooting, install...",Petaling,Engineering,Electrical/Electronic Engineering,services-engineer,Full time,"RM 3,000 – RM 3,500 per month",2024-03-22T05:32:09Z
4,74679363.0,Purchasing Executive,Magnet Security & Automation Sdn. Bhd.,"MAG is a trailblazer in the industry, boasting...",Hulu Langat,"Manufacturing, Transport & Logistics","Purchasing, Procurement & Inventory",purchasing-executive,Full time,"RM 2,800 – RM 3,500 per month",2024-03-23T03:56:39Z

In [ ]:
# First 10 rows with specific columns only# Display the first 10 records for selected key columns
df[["job_id", "job_title", "company", "location", "type", "salary", "listingDate"]].head(10)

,job_id,job_title,company,location,type,salary,listingDate
0,74630583.0,Procurement Executive (Contract),Coca-Cola Bottlers (Malaysia) Sdn Bhd,Negeri Sembilan,Contract/Temp,NaN,2024-03-21T05:58:35Z
1,74660602.0,Account Executive/ Assistant,Acoustic & Lighting System Sdn Bhd,Petaling,Full time,"RM 2,800 – RM 3,200 per month",2024-03-22T06:52:57Z
2,74655679.0,"Data Analyst - Asset Management, SPX Express",Shopee Mobile Malaysia Sdn Bhd,Klang District,Full time,NaN,2024-03-22T04:22:43Z
3,74657624.0,Service Engineer,Sun Medical Systems Sdn Bhd,Petaling,Full time,"RM 3,000 – RM 3,500 per month",2024-03-22T05:32:09Z
4,74679363.0,Purchasing Executive,Magnet Security & Automation Sdn. Bhd.,Hulu Langat,Full time,"RM 2,800 – RM 3,500 per month",2024-03-23T03:56:39Z
5,74661023.0,Accounts Executive,HPMT Industries Sdn Bhd,Shah Alam/Subang,Full time,NaN,2024-03-22T07:12:37Z
6,74677110.0,Accounts Executive,GENETEC TECHNOLOGY BERHAD,Kajang/Bangi/Serdang,Full time,"RM 3,000 – RM 4,500 per month",2024-03-23T00:22:28Z
7,74657915.0,PURCHASING EXECUTIVE,MINSEC ENGINEERING SDN. BHD.,Petaling,Full time,NaN,2024-03-22T05:44:08Z
8,74662794.0,Accounts Assistant (AP),KLK OLEO,Selangor,Full time,NaN,2024-03-22T08:30:54Z
9,74602737.0,Admin Assistant,Lein Hing Holdings Sdn Bhd,Kuala Lumpur,Full time,"RM 2,000 – RM 3,000 per month",2024-03-20T09:14:23Z

In [31]:
# Display 5 random records for selected key columns
df[["job_id", "job_title", "company", "location", "type", "salary", "listingDate"]].sample(5, random_state=42)

,job_id,job_title,company,location,type,salary,listingDate
14886,74030147.0,Electrical & Instrument Engineer,IMEC,Seberang Perai,Full time,NaN,2024-02-26T07:39:20Z
21842,74583187.0,Project Manager,KOOL ELEGANCE SDN BHD,Kuala Lumpur,Contract/Temp,NaN,2024-03-19T21:02:00Z
53575,76470165.0,Service Crew,Exact Management & Services Sdn Bhd,Mont Kiara,Full time,"RM 2,300 – RM 2,500 per month",2024-06-09T15:52:44Z
50853,76253221.0,"Executive, Product Marketing",KLCC (Holdings) Sdn Bhd,Kuala Lumpur,Full time,NaN,2024-05-30T05:47:15Z
5662,74392198.0,Piping Engineer,SWA WATER (MALAYSIA) SDN. BHD.,Kuala Lumpur,Full time,NaN,2024-03-12T07:59:06Z

In [ ]:
# Display sample job description text from random records
sample_descriptions = df["descriptions"].sample(3, random_state=42)

for i, desc in sample_descriptions.items():
    print(f"Row index: {i}")
    print(desc)
    print("\n" + "="*100 + "\n")

Row index: 14886
Electrical & Instrument Engineer
Job Description:
Responsibilities:
•           Plan,
implement, control, maintain and updates the electrical-related process when
needed.
•           Plan
and manage the replacement, improvement and alteration of electrical plant
& equipment.
•           Maintain
and update the asset register or electrical plant and equipment.
•           Identify
technical problems and react promptly with solutions and recommendations.
•           Handling
and troubleshooting all electrical plants and equipment.
•           Schedule
of preventative maintenance works.
•           Train
fellow employees/technicians with appropriate technical knowledge of PLC
(Ladder diagram), HMI, Servo motor, Inverter and other electrical equipment.
•           Coordinate
with electrical and instrumentation equipment vendors, to ensure compliance
with project specifications. Selection of electrical equipment types, cable
sizes and protection types and review drawings, calculations, design reports,
etc. by vendors
•           Provide
support on in-house control panel / electrical design, site electrical
installation, testing and commissioning, or servicing jobs related to
electrical and control packages at customers’ premises.
•           Support
quality department in troubleshooting quality incidents, and provide technical
solutions for manufacturing issues or customer issues.
•           Undertake,
coordinate and timely execute any other assigned task or projects from time to
time.
•           Contributes
to team effort by accomplishing related results as needed.
•           To
promote high teamwork spirit and uphold hormones working environment among all
team members and employees in the company.
•           To
be committed and play positive roles toward achieving the Company’s mission and
vision
•           To
promote high teamwork spirit and uphold hormones working environment among all
team members and employees in the company.
•           To
be committed and play positive roles toward achieving the Company's mission and
vision.
•           To
take up any other tasks and/or responsibilities not stated above, as instructed
by superiors from time to time.
Qualification and Experience:
-
Diploma or
Degree in Engineering (Electrical or Automation or Electronics) with a minimum
of
5 years
of working experience in relevant fields.
-
Candidates possess
Competency from TNB, Suruhanjaya Tenaga (ST) for Professional A1/A4/AO
chargeman Certificates will be an advantage.
-
Proficient
in all MS Office applications and ZWCAD, SOLIDWORKS drawing applications.
-
To have
technical knowledge of PLC and highly skilled with instrumentation, diagnostic
and ability to troubleshoot.
Summary of role requirements:
Looking for candidates available to work:
Monday: Morning
Tuesday: Morning
Wednesday: Morning
Thursday: Morning
Friday: Morning
2-3 years of relevant work experience required for this role
Working rights required for this role
Expected start date for role: 15 March 2024
Expected salary: RM3,200 - RM5,000 per month

====================================================================================================

Row index: 21842
Description
Roles and Responsibilities:
1. Lead and manage IT projects from initiation to completion, ensuring timely delivery within scope and budget.
2. Collaborate with stakeholders to define project objectives, scope, and requirements.
3. Develop project plans, schedules, and budgets, and allocate resources accordingly.
4. Monitor project progress, identify risks and issues, and implement effective mitigation strategies.
5. Communicate project status, updates, and issues to stakeholders and senior management.
6. Foster a collaborative and positive team environment, motivating team members to achieve project goals.
7. Ensure compliance with project management best practices, company policies, and industry standards.
8. Continuously improve project management processes and methodologies.
Requirements:
- Bachelor's degree in Computer Science, Information Technology, or related field.
- Proven experience 5 years and above as an IT Project Manager or similar role, with a successful track record of delivering projects on time and within budget.
- Strong leadership, communication, and interpersonal skills.
- Excellent problem-solving and decision-making abilities.
- Proficiency in project management tools and methodologies (e.g., Agile, Waterfall).
- Certification in Project Management (PMP, PRINCE2) is a plus.
- Experience in Service Now Project Management Tool and Certified in Service Now platform
Company
Kool Elegance Sdn Bhd is MSC status company in Malaysia located in Kuala Lumpur having offices in India and USA. Kool Elegance Sdn Bhd, is one among the leading IT & Telecom solutions company in Malaysia also having presencefor the last few years experience in developing innovative solutions to many SME & Fortune 500 companies. At Kool Elegance, we have distilled the key elements of successful projects and honed our solutions to meet customer needs. Our three key main objectives:
Technology Based Business Innovation, Business optimization, IT optimisation.

====================================================================================================

Row index: 53575
About Us:
At REBEL PASTA, we believe that dining is an experience that goes beyond great food. Our mission is to create memorable moments for our guests through exceptional service, delectable cuisine, and a warm, inviting atmosphere. We're not just serving meals; we're crafting experiences, one plate at a time.
The Role:
Are you passionate about food and thrive in a fast-paced, dynamic environment? We're on the lookout for enthusiastic and dedicated Servers to join our team. As a Server at REBEL PASTA, you'll be the face of our restaurant, providing outstanding service and ensuring our guests leave with smiles on their faces and a desire to return.
What You'll Do:
- Create Lasting Impressions:Greet guests with a friendly smile and genuine warmth, setting the tone for a fantastic dining experience.
- Menu Maestro:Master our menu and wine list, offering insightful recommendations and answering any questions with confidence.
- Service Excellence:Take orders accurately, deliver food and beverages promptly, and ensure every guest's needs are met with attentive and personalized service.
- Ambassador of Ambiance:Maintain a clean and organized dining area, contributing to the restaurant's inviting atmosphere.
- Team Collaboration: Work harmoniously with kitchen staff and fellow servers to ensure seamless service and a cohesive dining experience.
- Problem-Solving Pro:Handle guest concerns with grace and efficiency, turning any issue into a positive resolution.
What We Offer:
- Competitive Pay:Excellent base salary plus tips.
- Growth Opportunities: We believe in promoting from within and offer career development paths.
- Team Environment:Join a supportive, fun-loving team that values collaboration and mutual respect.
- Perks & Benefits:Enjoy employee discounts, meals, and other exciting perks.
What We're Looking For:
People Person: Excellent communication and interpersonal skills with a knack for making guests feel welcome.
Detail-Oriented:Keen eye for detail to ensure orders are accurate and service standards are upheld.
Positive Attitude:Energetic, enthusiastic, and a true team player.
Experience Preferred:Prior serving experience is a plus, but a great attitude and willingness to learn are essential.
Adaptability:Ability to thrive in a fast-paced environment and handle stressful situations with poise.
How to Apply:
Ready to become part of the REBEL PASTA family? Send your resume and a brief cover letter explaining why you'd be a great fit for this role to
[email protected]
or apply in person at REBEL PASTA 163 RETAIL PARK, MONT KIARA.

====================================================================================================

In [32]:
# Calculate the number and percentage of missing values for each column
missing_count = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

# Combine missing value results into a summary table
missing_summary = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing Percentage": missing_percent.round(2)
})

# Sort columns by missing value count in descending order
missing_summary = missing_summary.sort_values(by="Missing Count", ascending=False)
missing_summary

              Missing Count  Missing Percentage
salary                37430               54.23
role                   2252                3.26
job_id                    0                0.00
company                   0                0.00
job_title                 0                0.00
descriptions              0                0.00
location                  0                0.00
subcategory               0                0.00
category                  0                0.00
type                      0                0.00
listingDate               0                0.00

In [ ]:
# Identify the number of unique values
categorical_cols = ["type", "category", "subcategory", "role"]

for col in categorical_cols:
    print(f"{col}: {df[col].nunique()} unique values")

type: 11 unique values
category: 30 unique values
subcategory: 310 unique values
role: 5484 unique values

In [ ]:
# Display category values and their frequencies
print("Type value counts:")
print(df["type"].value_counts(dropna=False))

print("\nCategory value counts:")
print(df["category"].value_counts(dropna=False))

print("\nSubcategory value counts:")
print(df["subcategory"].value_counts(dropna=False))

# Display the 20 most frequent values in the role column
print("\nTop 20 role value counts:")
print(df["role"].value_counts(dropna=False).head(20))

Type value counts:
type
Full time                                      53790
['Full time']                                   9030
Contract/Temp                                   4976
['Contract/Temp']                                584
Part time                                        289
Casual/Vacation                                  251
['Part time']                                     78
['Casual/Vacation']                               22
['Contract/Temp', 'Full time']                     2
['Full time', 'Part time']                         1
['Contract/Temp', 'Full time', 'Part time']        1
Name: count, dtype: int64

Category value counts:
category
Accounting                                11308
Engineering                                8978
Information & Communication Technology     8675
Administration & Office Support            7101
Sales                                      5715
Manufacturing, Transport & Logistics       5388
Human Resources & Recruitment              4055
Marketing & Communications                 3004
Banking & Financial Services               2641
Call Centre & Customer Service             1792
Construction                               1621
Retail & Consumer Products                 1504
Hospitality & Tourism                       974
Healthcare & Medical                        910
Design & Architecture                       879
Education & Training                        810
Real Estate & Property                      705
Trades & Services                           600
Science & Technology                        551
Advertising, Arts & Media                   416
Legal                                       374
Consulting & Strategy                       315
Insurance & Superannuation                  225
Mining, Resources & Energy                  127
CEO & General Management                    120
Farming, Animals & Conservation             106
Sport & Recreation                           45
Community Services & Development             44
Government & Defence                         40
Self Employment                               1
Name: count, dtype: int64

Subcategory value counts:
subcategory
Administrative Assistants                     4655
Bookkeeping & Small Practice Accounting       3845
Financial Accounting & Reporting              3292
Management                                    2755
Consulting & Generalist HR                    2398
                                              ...
Plumbers                                         1
Nursing - Midwifery, Neo-Natal, SCN & NICU       1
Oil & Gas - Exploration & Geoscience             1
Tailors & Dressmakers                            1
Butchers                                         1
Name: count, Length: 310, dtype: int64

Top 20 role value counts:
role
NaN                           2252
account-executive             1483
sales-executive               1221
accounts-executive            1198
administration-officer        1116
Executive                      951
human-resource-executive       919
administrative-executive       826
finance-executive              736
marketing-executive            643
administration                 625
engineer                       556
project-engineer               545
account-assistant              509
software-engineer              499
accountant                     447
customer-service-executive     446
assistant-manager              436
manager                        411
technician                     408
Name: count, dtype: int64

In [ ]:
# Inspect records where employment type is stored in list-like string format
df[df["type"].str.contains(r"\[", na=False)][["job_title", "type"]].head(20)

                                               job_title           type
59306                            Booth Crew (Theme Park)  ['Full time']
59307          UNIT TRUST CONSULTANT PART-TIME/FULL-TIME  ['Full time']
59308                        Shift Production Supervisor  ['Full time']
59309                                        Bread Baker  ['Full time']
59310                                         Accountant  ['Full time']
59311  Customer Service Specialist - Mandarin Speaker...  ['Full time']
59312                                    Account Officer  ['Full time']
59313                           Partner Alliance Manager  ['Full time']
59314                                     Manager - RISQ  ['Full time']
59315                                    ADMIN EXECUTIVE  ['Full time']
59316                     Manager, Logistics & Warehouse  ['Full time']
59317                     Business Development Executive  ['Full time']
59318  Senior Executive or Assistant Manager, Corpora...  ['Full time']
59319              IT Analyst (Development & Operations)  ['Full time']
59320                                 Accounts Executive  ['Full time']
59321            EOI:BO Chargeman, 11KV or 33KV (Penang)  ['Full time']
59322                           Property Sales Executive  ['Full time']
59323  Factory Manager (Manufacturing Company in Pena...  ['Full time']
59324                                  Library Assistant  ['Full time']
59325                        Marketing Manager (Product)  ['Full time']

In [ ]:
# Inspect records with multiple employment types in the same field
df[df["type"].str.contains(",", na=False)][["job_title", "type"]].head(20)

,job_title,type
59464,Office Administration & Engagement Executive (...,"['Contract/Temp', 'Full time']"
62032,Customer Care Specialist,"['Full time', 'Part time']"
63404,Mandarin Teacher 中文老师,"['Contract/Temp', 'Full time', 'Part time']"
65402,Onboarding Executive - APMEA/Europe (1 year co...,"['Contract/Temp', 'Full time']"

In [ ]:
# Check the number of unique location values
print("Number of unique locations:", df["location"].nunique())

Number of unique locations: 647

In [ ]:
# Display the 30 most frequent location values
df["location"].value_counts().head(30)

location
Kuala Lumpur                              15390
Petaling                                   9746
Johor Bahru District                       4480
Selangor                                   2842
Shah Alam/Subang                           2621
Kuala Lumpur City Centre                   2112
Penang                                     1930
Penang Island                              1885
Seberang Perai                             1796
Klang District                             1427
Hulu Langat                                 958
Kajang/Bangi/Serdang                        937
Sepang                                      865
Kota Kinabalu District                      805
Kinta District                              776
Kuching Division                            770
Johor                                       729
Seremban District                           638
Kulai District                              628
Petaling Jaya, Selangor                     519
Bangsar South                               514
Gombak District                             484
Klang/Port Klang                            468
Kulim District                              442
Johor Bahru, Johor                          439
Kuala Lumpur City Centre, Kuala Lumpur      438
Melaka                                      433
Melaka Tengah                               425
Kuantan District                            305
Bukit Jalil                                 304
Name: count, dtype: int64

In [ ]:
# Inspect location values that contain a slash
df[df["location"].str.contains("/", na=False)][["job_title", "location"]].head(20)

                                             job_title              location
5                                   Accounts Executive      Shah Alam/Subang
6                                   Accounts Executive  Kajang/Bangi/Serdang
17                              Admin cum HR Executive      Shah Alam/Subang
22                         Account cum Admin Executive      Shah Alam/Subang
56                               Procurement Executive      Shah Alam/Subang
61                      Admin cum logistic coordinator      Shah Alam/Subang
100                                    ADMIN ASSISTANT      Shah Alam/Subang
110                                       Office Admin      Shah Alam/Subang
120                                    Admin Assistant  Kajang/Bangi/Serdang
160                           Accounts Payable Officer      Shah Alam/Subang
170  Credit Administration Supervisor/ Executive - ...      Shah Alam/Subang
175                        Executive, Value Management      Shah Alam/Subang
179       ACCOUNT EXECUTIVE - GLOBAL BUSINESS SERVICES      Shah Alam/Subang
187                                    Admin Assistant      Shah Alam/Subang
188                                       HR Executive      Shah Alam/Subang
191                                    JURUTEKNIK TCST      Shah Alam/Subang
202                                 Accounts Executive  Kajang/Bangi/Serdang
214                             Administration Manager      Shah Alam/Subang
239                             Environmental Engineer      Shah Alam/Subang
258                  Assistant Business System Manager      Shah Alam/Subang

In [ ]:
# Inspect location values that contain a comma
df[df["location"].str.contains(",", na=False)][["job_title", "location"]].head(20)

,job_title,location
693,Manufacturing Engineer ( Management Trainee ),"Larut, Matang and Selama District"
1385,HR & Admin,"Larut, Matang and Selama District"
2584,MCTF 2024 at Mid Valley Exhibition Centre (30-...,"Larut, Matang and Selama District"
2959,Executive - Sustainability Compliance and Cert...,"Larut, Matang and Selama District"
4822,ADMIN ASSISTANT,"Larut, Matang and Selama District"
4855,Admin Assistant,"Larut, Matang and Selama District"
4994,HR Clerk,"Larut, Matang and Selama District"
7157,Accountant,"Larut, Matang and Selama District"
7960,Human Resources Executive,"Larut, Matang and Selama District"
8394,PHP Developer,"Larut, Matang and Selama District"
8841,Project Manager,"Larut, Matang and Selama District"
10160,R&D Process Officer,"Larut, Matang and Selama District"
10459,Site Safety Supervisor,"Larut, Matang and Selama District"
12801,Senior HRBP Manager,"Larut, Matang and Selama District"
14083,Trainer,"Larut, Matang and Selama District"
14654,ACCOUNTING ASSISTANCE,"Larut, Matang and Selama District"
14741,Quality Engineer,"Larut, Matang and Selama District"
14817,Repair & Maintenance Engineer,"Larut, Matang and Selama District"
14951,Technician,"Larut, Matang and Selama District"
15399,Admin & Account Clerk (Logistic and Transport)...,"Larut, Matang and Selama District"

In [ ]:
# Check for fully duplicated records across all columns
full_duplicates = df.duplicated().sum()
print("Number of fully duplicated rows:", full_duplicates)

Number of fully duplicated rows: 0

In [ ]:
# Check for duplicated job_id values
job_id_duplicates = df["job_id"].duplicated().sum()
print("Number of duplicated job_id values:", job_id_duplicates)

Number of duplicated job_id values: 0

In [ ]:
# Inspect sample non missing salary values
df["salary"].dropna().sample(20, random_state=42)

60990      RM 6,000 – RM 8,500 per month
7582       RM 6,000 – RM 8,000 per month
4502       RM 2,800 – RM 3,500 per month
16670      RM 2,500 – RM 3,500 per month
4267      RM 8,000 – RM 11,000 per month
27487      RM 2,500 – RM 2,700 per month
40745    RM 15,000 – RM 20,000 per month
44255    RM 11,000 – RM 13,500 per month
9621       RM 4,500 – RM 5,000 per month
3131       RM 2,500 – RM 3,500 per month
27957        RM 700 – RM 1,000 per month
64134     RM 8,000 – RM 12,000 per month
28525      RM 4,000 – RM 5,000 per month
45135      RM 2,000 – RM 2,600 per month
6392       RM 3,000 – RM 4,000 per month
9035       RM 4,500 – RM 5,500 per month
3019       RM 4,000 – RM 5,000 per month
68586      RM 2,500 – RM 3,500 per month
56671      RM 4,500 – RM 6,500 per month
34748      RM 3,000 – RM 4,000 per month
Name: salary, dtype: str

In [ ]:
# Display the most frequent salary values
df["salary"].value_counts().head(20)

salary
RM 3,000 – RM 4,500 per month     1750
RM 4,000 – RM 6,000 per month     1469
RM 3,500 – RM 5,000 per month     1443
RM 2,500 – RM 3,500 per month     1301
RM 3,000 – RM 4,000 per month     1225
RM 3,500 – RM 4,500 per month      838
RM 2,000 – RM 3,000 per month      778
RM 2,500 – RM 3,000 per month      613
RM 5,000 – RM 7,000 per month      606
RM 4,000 – RM 5,000 per month      604
RM 3,000 – RM 3,500 per month      520
RM 2,000 – RM 2,500 per month      449
RM 2,800 – RM 4,000 per month      414
RM 6,000 – RM 8,000 per month      409
RM 5,000 – RM 7,500 per month      398
RM 4,000 – RM 5,500 per month      378
RM 2,800 – RM 3,500 per month      354
RM 6,000 – RM 9,000 per month      323
RM 8,000 – RM 12,000 per month     317
RM 4,500 – RM 6,000 per month      312
Name: count, dtype: int64

In [ ]:
# Check the salary period terms used in the salary text
print("Contains 'month':", df["salary"].str.contains("month", case=False, na=False).sum())
print("Contains 'year':", df["salary"].str.contains("year", case=False, na=False).sum())
print("Contains 'day':", df["salary"].str.contains("day", case=False, na=False).sum())
print("Contains 'hour':", df["salary"].str.contains("hour", case=False, na=False).sum())

Contains 'month': 30121
Contains 'year': 91
Contains 'day': 0
Contains 'hour': 52

In [ ]:
# Check the symbols used to express salary ranges
print("Contains '-' :", df["salary"].str.contains("-", na=False).sum())
print("Contains '–' :", df["salary"].str.contains("–", na=False).sum())

Contains '-' : 1235
Contains '–' : 29728

In [ ]:
# Inspect unique salary examples to identify currency and format variations
salary_examples = df["salary"].dropna().drop_duplicates()
salary_examples.sample(30, random_state=42)

43711                            MYR 2,400 - 3,300
9297               RM 20,000 – RM 26,000 per month
35396                      $9000.0 - $11000.0 p.m.
17356                            MYR 2,800 - 3,920
56694                    $2,000 – $2,500 per month
33434                                  RM10K-RM12K
35997                            SGD 2,500 - 3,100
11504                          RM 10000 - RM 20000
32092                    RM 800 – RM 875 per month
3310                               $5k - $10k p.m.
2163     $36k - $64k p.a. + Bonus + Other benefits
34515                            MYR 4,000 - 4,800
34916                                 RM9k - RM11k
18491                            MYR 5,500 - 7,000
321                             RM 1,000 per month
11451                RM 1,700 – RM 2,400 per month
7104                               $9k - $15k p.m.
39814                            MYR 2,900 - 4,000
36548                           $160k - $168k p.a.
398                RM 10,000 – RM 12,000 per month
7812                           MYR 18,000 - 21,000
439                  RM 2,300 – RM 3,300 per month
11520                            MYR 2,600 - 3,700
2234                RM 9,000 – RM 12,000 per month
1263                RM 9,000 – RM 13,500 per month
1410               RM 10,500 – RM 15,000 per month
28815                RM 5,500 – RM 6,800 per month
5210                 RM 2,900 – RM 4,300 per month
38524              RM 12,500 – RM 14,000 per month
2943                              $15k - $23k p.m.
Name: salary, dtype: str

In [ ]:
# Inspect records with unusual salary notation or currency format
df[
    df["salary"].notna() &
    df["salary"].str.contains(r"MYR|\$|SGD|\d+\s*[kK]", case=False, na=False, regex=True)
][["job_title", "salary"]].head(30)

,job_title,salary
32,HR & Admin Manager,"MYR 6,500 - 7,500"
93,HR & Admin Assistant Manager/Manager,"MYR 4,500 - 6,000"
94,Operations Executive,"MYR 2,000 - 2,500"
134,Admin Executive (Open to Fresh Graduate),"MYR 2,000 - 3,000"
375,ERP SYSTEM CONSULTANT (Mandarin Speaker - Fres...,"MYR 3,000 - 3,500"
386,IT Executive,"MYR 2,400 - 3,400"
413,Accounts Executive / Administrative Officer,"MYR 2,700 - 3,800"
418,FINANCE EXECUTIVE,"MYR 2,400 - 3,360"
431,Building Technician (URGENT HIRING),"MYR 2,500 - 3,500"
448,Site Engineer/ Project Engineer/ Site Supervisor,"MYR 2,500 - 3,500"
478,Human Resources (HR) Internship,"MYR 800 - 1,000"
515,ACCOUNTS EXECUTIVE,"MYR 2,500 - 3,500"
595,Finance Associate,"MYR 3,000 - 4,000"
627,Audit Executive,"MYR 2,600 - 3,000"
754,Admin cum Accounts Executive,"$2,300 – $3,200 per month"
760,Cost Controller (MNC Oil & Gas),MYR 9k - MYR 13k p.m.
784,HR CUM ACCOUNT ADMIN,"MYR 2,000 - 2,800"
833,Sales Executive,"MYR 3,000 - 4,500"
853,Invoicing Coordinator - Fresh graduates are we...,$3200 - $3500 p.m.
872,Project Manager (ID - Office),"$6k - $10k p.m. + Competitive, Great Exposure"
899,Purchasing Executive,"MYR 3,500 - 4,900"
940,Junior Accountant,"MYR 2,500 - 3,500"
973,Project Admin Assistant,"MYR 2,500 - 3,500"
981,Software Engineer (Frontend),"MYR 5,500 - 8,000"
1068,Admin Executive,"MYR 3,000 - 3,500"
1169,"AP Specialist - Global Company (Muar, Johor)",$5500 - $6k p.m.
1177,Tax Specialist,RM8k - RM10k
1193,Audit Associate 审计助理 (Fresh Grad Welcome!!) Mi...,"MYR 3,000 - 4,200"
1203,Accounts Executive cum HR,"MYR 3,000 - 4,200"
1226,PTP Accounts Payable Analyst - AP - MNC/SSC,$3800 - $5500 p.m.

In [ ]:
# Inspect sample values in the listing date column
df["listingDate"].head(10)

0    2024-03-21T05:58:35Z
1    2024-03-22T06:52:57Z
2    2024-03-22T04:22:43Z
3    2024-03-22T05:32:09Z
4    2024-03-23T03:56:39Z
5    2024-03-22T07:12:37Z
6    2024-03-23T00:22:28Z
7    2024-03-22T05:44:08Z
8    2024-03-22T08:30:54Z
9    2024-03-20T09:14:23Z
Name: listingDate, dtype: str

In [ ]:
# Convert listingDate to datetime format for validation and summary checks
listing_date_parsed = pd.to_datetime(df["listingDate"], errors="coerce")

print("Missing after datetime conversion:", listing_date_parsed.isnull().sum())
print("Earliest listing date:", listing_date_parsed.min())
print("Latest listing date:", listing_date_parsed.max())

Missing after datetime conversion: 0
Earliest listing date: 2023-03-23 19:44:00+00:00
Latest listing date: 2025-05-08 11:12:22+00:00

In [ ]:
# Review the distribution of records by listing year
listing_date_parsed.dt.year.value_counts().sort_index()

listingDate
2023     1717
2024    57589
2025     9718
Name: count, dtype: int64